export const daftarKota = [
  // Banten
  "Kabupaten Pandeglang",
  "Kabupaten Lebak",
  "Kabupaten Tangerang",
  "Kabupaten Serang",
  "Kota Tangerang",
  "Kota Cilegon",
  "Kota Serang",
  "Kota Tangerang Selatan",

  // DKI Jakarta
  "Jakarta Pusat",
  "Jakarta Utara",
  "Jakarta Barat",
  "Jakarta Selatan",
  "Jakarta Timur",

  // Jawa Barat
  "Kabupaten Bogor",
  "Kabupaten Sukabumi",
  "Kabupaten Cianjur",
  "Kabupaten Bandung",
  "Kabupaten Garut",
  "Kabupaten Tasikmalaya",
  "Kabupaten Ciamis",
  "Kabupaten Kuningan",
  "Kabupaten Cirebon",
  "Kabupaten Majalengka",
  "Kabupaten Sumedang",
  "Kabupaten Indramayu",
  "Kabupaten Subang",
  "Kabupaten Purwakarta",
  "Kabupaten Karawang",
  "Kabupaten Bekasi",
  "Kabupaten Bandung Barat",
  "Kabupaten Pangandaran",
  "Kota Bogor",
  "Kota Sukabumi",
  "Kota Bandung",
  "Kota Cirebon",
  "Kota Bekasi",
  "Kota Depok",
  "Kota Cimahi",
  "Kota Tasikmalaya",
  "Kota Banjar",

  // Jawa Tengah
  "Kabupaten Cilacap",
  "Kabupaten Banyumas",
  "Kabupaten Purbalingga",
  "Kabupaten Banjarnegara",
  "Kabupaten Kebumen",
  "Kabupaten Purworejo",
  "Kabupaten Wonosobo",
  "Kabupaten Magelang",
  "Kabupaten Boyolali",
  "Kabupaten Klaten",
  "Kabupaten Sukoharjo",
  "Kabupaten Wonogiri",
  "Kabupaten Karanganyar",
  "Kabupaten Sragen",
  "Kabupaten Grobogan",
  "Kabupaten Blora",
  "Kabupaten Rembang",
  "Kabupaten Pati",
  "Kabupaten Kudus",
  "Kabupaten Jepara",
  "Kabupaten Demak",
  "Kabupaten Semarang",
  "Kabupaten Temanggung",
  "Kabupaten Kendal",
  "Kabupaten Batang",
  "Kabupaten Pekalongan",
  "Kabupaten Pemalang",
  "Kabupaten Tegal",
  "Kabupaten Brebes",
  "Kota Magelang",
  "Kota Surakarta",
  "Kota Salatiga",
  "Kota Semarang",
  "Kota Pekalongan",
  "Kota Tegal",

  // DI Yogyakarta
  "Kabupaten Kulon Progo",
  "Kabupaten Bantul",
  "Kabupaten Gunungkidul",
  "Kabupaten Sleman",
  "Kota Yogyakarta",

  // Jawa Timur
  "Kabupaten Pacitan",
  "Kabupaten Ponorogo",
  "Kabupaten Trenggalek",
  "Kabupaten Tulungagung",
  "Kabupaten Blitar",
  "Kabupaten Kediri",
  "Kabupaten Malang",
  "Kabupaten Lumajang",
  "Kabupaten Jember",
  "Kabupaten Banyuwangi",
  "Kabupaten Bondowoso",
  "Kabupaten Situbondo",
  "Kabupaten Probolinggo",
  "Kabupaten Pasuruan",
  "Kabupaten Sidoarjo",
  "Kabupaten Mojokerto",
  "Kabupaten Jombang",
  "Kabupaten Nganjuk",
  "Kabupaten Madiun",
  "Kabupaten Magetan",
  "Kabupaten Ngawi",
  "Kabupaten Bojonegoro",
  "Kabupaten Tuban",
  "Kabupaten Lamongan",
  "Kabupaten Gresik",
  "Kabupaten Bangkalan",
  "Kabupaten Sampang",
  "Kabupaten Pamekasan",
  "Kabupaten Sumenep",
  "Kota Kediri",
  "Kota Blitar",
  "Kota Malang",
  "Kota Probolinggo",
  "Kota Pasuruan",
  "Kota Mojokerto",
  "Kota Madiun",
  "Kota Surabaya",
  "Kota Batu",
];
